apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openbi

resources:
  - namespace.yaml
  - postgres-deployment.yaml
  - fastapi-deployment.yaml
  - superset-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: openbi-platform
  app.kubernetes.io/managed-by: kustomize
