apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress-routes.yaml

commonLabels:
  app.kubernetes.io/part-of: openbi-platform
  app.kubernetes.io/managed-by: kustomize
